In [10]:
import numpy as np

In [12]:
q = np. array([0,1,2,3,4,5,6,7,8,9])
q

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
q = np.arange(10)
q

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.full((7, 7), False, dtype=bool)

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])

In [15]:
np.zeros((5,5), dtype=bool)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [16]:
np.ones((5,5), dtype=bool)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [17]:
np.full((9, 9), True, dtype=bool)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [19]:
q=np.arange(100)
q[a%2==1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [20]:
q=np.arange(100)
q[a%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [21]:
a=np.arange(100)
a[a%2==1]= -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14, -1, 16,
       -1, 18, -1, 20, -1, 22, -1, 24, -1, 26, -1, 28, -1, 30, -1, 32, -1,
       34, -1, 36, -1, 38, -1, 40, -1, 42, -1, 44, -1, 46, -1, 48, -1, 50,
       -1, 52, -1, 54, -1, 56, -1, 58, -1, 60, -1, 62, -1, 64, -1, 66, -1,
       68, -1, 70, -1, 72, -1, 74, -1, 76, -1, 78, -1, 80, -1, 82, -1, 84,
       -1, 86, -1, 88, -1, 90, -1, 92, -1, 94, -1, 96, -1, 98, -1])

In [22]:
a=np.arange(100)
a[a%2==0]=2
a

array([ 2,  1,  2,  3,  2,  5,  2,  7,  2,  9,  2, 11,  2, 13,  2, 15,  2,
       17,  2, 19,  2, 21,  2, 23,  2, 25,  2, 27,  2, 29,  2, 31,  2, 33,
        2, 35,  2, 37,  2, 39,  2, 41,  2, 43,  2, 45,  2, 47,  2, 49,  2,
       51,  2, 53,  2, 55,  2, 57,  2, 59,  2, 61,  2, 63,  2, 65,  2, 67,
        2, 69,  2, 71,  2, 73,  2, 75,  2, 77,  2, 79,  2, 81,  2, 83,  2,
       85,  2, 87,  2, 89,  2, 91,  2, 93,  2, 95,  2, 97,  2, 99])

In [24]:
a = np.arange(100)
b = np.reshape(a, (2, -1))
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [25]:

a = np.arange(26)
b = np.reshape(a, (-1, 2))
b

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25]])

In [26]:

a = np.arange(26).reshape(2, -1)
b = np.repeat(1, 26).reshape(2, -1)
np.vstack((a, b))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1]])

In [27]:
a = np.arange(26).reshape(2, -1)
b = np.repeat(1, 26).reshape(2, -1)
np.concatenate([a, b], axis=0)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1]])

In [28]:

a = np.arange(26).reshape(2, -1)
b = np.repeat(1, 26).reshape(2, -1)
np.r_[a, b]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1]])

In [29]:
a = np.arange(26).reshape(2,-1)
b = np.repeat(1, 26).reshape(2,-1)
np.hstack((a,b))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1]])

In [31]:
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
np.r_[np.repeat(a,6)]

array([1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4,
       4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 8, 8,
       8, 8, 8, 8, 9, 9, 9, 9, 9, 9])

In [32]:
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
np.r_[np.tile(a, 6)]

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
       5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8,
       9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
b = np.array([1,3,5,7,9,11,13,15,17,19])
np.intersect1d(a,b)

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [34]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
b = np.array([1,3,5,7,9,11,13,15,17,19])
np.setdiff1d(a, b)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [35]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
b = np.array([1,3,5,7,9,11,13,15,17,19])
np.setdiff1d(b, a)

array([17, 19])

In [36]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
b = np.array([1,3,5,7,5,11,13,15,17,19,11,23,25,27,29,31])
np.where(a==b)

(array([ 0,  4, 10], dtype=int64),)

In [37]:
b = np.array([10,3,5,2,1,7,3,4,0,1,5,25,8,20,12,11])
b[(b >= 5) & (b <= 25)]

array([10,  5,  7,  5, 25,  8, 20, 12, 11])

In [38]:
b = np.array([10,3,5,2,1,7,3,4,0,1,5,25,8,20,12,11])
index = np.where(np.logical_and(b>=5, b<=25))
index

(array([ 0,  2,  5, 10, 11, 12, 13, 14, 15], dtype=int64),)

In [39]:
b = np.array([10,3,5,2,1,7,3,4,0,1,5,25,8,20,12,11])
index = np.where((b >=5) & (b <=25))
index

(array([ 0,  2,  5, 10, 11, 12, 13, 14, 15], dtype=int64),)

In [40]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
b = np.array([1,3,5,7,5,11,13,15,17,19,11,23,24,14,29,16])
np.where(a!=b)

(array([ 1,  2,  3,  5,  6,  7,  8,  9, 11, 12, 14], dtype=int64),)

In [41]:
def a(x, y):
    if x >= y:
        return x
    else:
        return y

combined = np.vectorize(a, otypes=[float])
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
b = np.array([1,3,5,7,5,11,13,15,17,19,11,23,24,14,29,16])
combined(a, b)

array([ 1.,  3.,  5.,  7.,  5., 11., 13., 15., 17., 19., 11., 23., 24.,
       14., 29., 16.])

In [42]:
arr=np.arange(9).reshape(3,3)
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [43]:
arr=np.arange(9).reshape(3,3)
arr[:,[2,0,1]]

array([[2, 0, 1],
       [5, 3, 4],
       [8, 6, 7]])

In [44]:
arr=np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [45]:
arr = np.arange(102).reshape(-1,3)
arr[:,::-1]

array([[  2,   1,   0],
       [  5,   4,   3],
       [  8,   7,   6],
       [ 11,  10,   9],
       [ 14,  13,  12],
       [ 17,  16,  15],
       [ 20,  19,  18],
       [ 23,  22,  21],
       [ 26,  25,  24],
       [ 29,  28,  27],
       [ 32,  31,  30],
       [ 35,  34,  33],
       [ 38,  37,  36],
       [ 41,  40,  39],
       [ 44,  43,  42],
       [ 47,  46,  45],
       [ 50,  49,  48],
       [ 53,  52,  51],
       [ 56,  55,  54],
       [ 59,  58,  57],
       [ 62,  61,  60],
       [ 65,  64,  63],
       [ 68,  67,  66],
       [ 71,  70,  69],
       [ 74,  73,  72],
       [ 77,  76,  75],
       [ 80,  79,  78],
       [ 83,  82,  81],
       [ 86,  85,  84],
       [ 89,  88,  87],
       [ 92,  91,  90],
       [ 95,  94,  93],
       [ 98,  97,  96],
       [101, 100,  99]])

In [46]:
arr = np.arange(25).reshape(5,5)
rdm_array=np.random.randint(low = 0, high = 1, size=(5,5)) + np.random.random((5,5))
print(rdm_array)

[[0.75447368 0.31376938 0.11443829 0.89837302 0.93882068]
 [0.3120188  0.47189817 0.46895818 0.31190815 0.07340391]
 [0.62798841 0.86856163 0.52033884 0.59389628 0.86894283]
 [0.37470328 0.35198959 0.27023562 0.42314539 0.50488863]
 [0.21996615 0.33711954 0.6602279  0.04386866 0.76588227]]


In [47]:
arr = np.arange(25).reshape(5,5)
rad_1 = np.random.uniform(0,5, size=(2,6))
print(rad_1)

[[0.80760815 2.69847725 3.81191663 1.47673115 3.12759087 1.71415984]
 [1.37804164 4.91055598 0.23684012 3.09683206 1.33975023 2.57669029]]


In [48]:
arr = np.arange(25).reshape(5,5)
rad_1 = np.random.uniform(0,5, size=(6,6))
np.set_printoptions(precision=3)
print(rad_1)
rad_1 [:4]

[[0.212 1.75  0.653 2.845 3.789 4.547]
 [4.731 1.281 2.023 2.576 2.458 0.916]
 [1.289 4.718 4.276 3.375 3.146 0.334]
 [3.31  3.92  3.276 1.829 3.77  4.941]
 [4.536 2.487 3.82  2.673 3.604 2.688]
 [0.135 3.592 2.775 1.58  0.731 0.014]]


array([[0.212, 1.75 , 0.653, 2.845, 3.789, 4.547],
       [4.731, 1.281, 2.023, 2.576, 2.458, 0.916],
       [1.289, 4.718, 4.276, 3.375, 3.146, 0.334],
       [3.31 , 3.92 , 3.276, 1.829, 3.77 , 4.941]])

In [49]:
np.set_printoptions(suppress=False)
np.random.seed(200)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[9.476e-04, 2.265e-04, 5.944e-04],
       [4.283e-04, 7.641e-04, 2.861e-06],
       [3.574e-04, 9.097e-04, 4.561e-04]])

In [50]:
np.set_printoptions(suppress=True, precision=6)
rand_arr

array([[0.000948, 0.000227, 0.000594],
       [0.000428, 0.000764, 0.000003],
       [0.000357, 0.00091 , 0.000456]])

In [51]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [52]:
arr = np.arange(25)
np.set_printoptions(threshold=np.sys.maxsize)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [53]:
b = np.array([10,3,5,2,1,7,3,4,0,1,5,25,8,20,12,11])
np.mean(b)

7.3125

In [54]:
b = np.array([10,3,5,2,1,7,3,4,0,1,5,25,8,20,12,11])
np.median(b)

5.0

In [55]:
b = np.array([10,3,5,2,1,7,3,4,0,1,5,25,8,20,12,11])
np.std(b)

6.788950121336877

In [56]:
b = np.array([10,3,5,2,1,7,3,4,0,1,5,25,8,20,12,11])
bmax, bmin = b.max(), b.min()
x = (b - bmin)/(bmax - bmin)
print (x)

[0.4  0.12 0.2  0.08 0.04 0.28 0.12 0.16 0.   0.04 0.2  1.   0.32 0.8
 0.48 0.44]


In [57]:
b = np.array([10,3,5,2,1,7,3,4,0,1,5,25,8,20,12,11])
bmax, bmin = b.max(), b.min()
x = (b - bmin)/b.ptp()
print (x)

[0.4  0.12 0.2  0.08 0.04 0.28 0.12 0.16 0.   0.04 0.2  1.   0.32 0.8
 0.48 0.44]


In [58]:
b = np.array([10,3,5,2,1,7,3,4,0,1,5,25,8,20,12,11])
np.percentile(b, q=[5, 95])

array([ 0.75, 21.25])

In [59]:

np.set_printoptions(precision=2)
np.random.seed(100)
a = np.random.uniform(1,80, 20)
np.clip(a, a_min=15, a_max=50)

array([43.93, 22.99, 34.54, 50.  , 15.  , 15.  , 50.  , 50.  , 15.  ,
       46.43, 50.  , 17.53, 15.64, 15.  , 18.36, 50.  , 50.  , 15.  ,
       50.  , 22.65])

In [60]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
a[a.argsort()][-5:]

array([41.  , 41.47, 42.39, 44.67, 48.95])

In [61]:
np.random.seed(100)
arr = np.random.randint(5,15,size=(7, 10))
arr

array([[13, 13,  8, 12, 12,  5,  9,  7, 10,  7],
       [ 7,  7,  6,  5, 13,  9,  5, 14, 11,  7],
       [ 9,  6, 10,  8,  9,  9,  8, 12,  6,  6],
       [12, 12,  5,  7, 14, 14,  8,  7, 10, 13],
       [ 6,  5, 12, 11,  7,  5, 13,  7, 10,  6],
       [13,  6, 10,  9,  7, 13,  8, 10,  5, 14],
       [ 8, 11,  8,  9, 12, 11,  8, 14,  5,  9]])

In [62]:
a = np.arange(5)
b = np.arange(2,5)
c = np.arange(4,8)

arr_of_arrs = np.array([a, b, c], dtype = object)
arr_of_arrs

array([array([0, 1, 2, 3, 4]), array([2, 3, 4]), array([4, 5, 6, 7])],
      dtype=object)

In [63]:
a = np.arange(5)
b = np.arange(2,5)
c = np.arange(4,8)
arr_of_arrs = np.array([a, b, c], dtype = object)
arr = np.concatenate(arr_of_arrs)
arr

array([0, 1, 2, 3, 4, 2, 3, 4, 4, 5, 6, 7])

In [66]:
a = np.array([[4,3,43],[2,7,4],[5,5,5],[6,6,6],[7,5,7]])
b = np.array([1,2,3,4,5])
c=a - b[:,None]             
print(c)

[[ 3  2 42]
 [ 0  5  2]
 [ 2  2  2]
 [ 2  2  2]
 [ 2  0  2]]
